version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: MemoApp
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "33066:3306"
    volumes:
      - ./data:/var/lib/mysql